/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PluginSystem */

#ifndef _Included_PluginSystem
#define _Included_PluginSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PluginSystem
 * Method:    initPluginManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PluginSystem_initPluginManager
  (JNIEnv *, jobject);

/*
 * Class:     PluginSystem
 * Method:    loadPlugin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_loadPlugin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PluginSystem
 * Method:    unloadPlugin
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_unloadPlugin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PluginSystem
 * Method:    loadAllPlugins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_loadAllPlugins
  (JNIEnv *, jobject);

/*
 * Class:     PluginSystem
 * Method:    unloadAllPlugins
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_unloadAllPlugins
  (JNIEnv *, jobject);

/*
 * Class:     PluginSystem
 * Method:    execPluginCommand
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_execPluginCommand
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     PluginSystem
 * Method:    execPluginAction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_PluginSystem_execPluginAction
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     PluginSystem
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PluginSystem_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     PluginSystem
 * Method:    printPlugins
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_PluginSystem_printPlugins
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
